### PR TITLE
Added labelsSortByValue option so that the legend will display series…

### PR DESCRIPTION
**Pull request by chadwickh**
… by y Value, in decreasing order

### CODE REVIEW

**Comment by danvk** [comment]
This feels overly specific. What would really be helpful is some way to plug in your own labels --> HTML converter.

**Comment by chadwickh** [comment]
Would an option legendFormatter that takes a function and returns the formatted HTML make sense?

**Comment by danvk** [comment]
Yes, that would be more reasonable.

**Comment by danvk** [comment]
This is #407

**Pull request closed without merging**
