### PR TITLE
Crosshair

### PR DESCRIPTION
**Pull request by pshevtsov**
This PR introduces using crosshair as a plugin

[Review on Reviewable](https://reviewable.io/reviews/danvk/dygraphs/299)

### CODE REVIEW

**Comment by pshevtsov** [comment]
Hey @danvk!

Any feedback on this issue?

Thanks!

**Comment by danvk** [comment]
Did something get mixed up in this PR? I'm seeing `extras/canvas-annotations.js` and other unrelated changes. I'm happy to punt on the legend question & merge this in.

**Comment by pshevtsov** [comment]
@danvk Yes, indeed something went wrong, sorry. I've just updated the source tree and added some improvements.

**Comment by danvk** [comment]
I'm going to go ahead and merge this in via #588. The commit history on this PR is a bit of a mess, so I've squashed it all into one commit.

Thanks for the change! If you'd like to add some documentation or additional options for styling the crosshairs, that would make for a welcome follow-up PR.

**Pull request closed without merging**
