### PR TITLE
Additional granularities and tick placements (2yr, 5yr)

### PR DESCRIPTION
**Pull request by fungl164**

### CODE REVIEW

**Comment by danvk** [comment]
Can you include some before/after screenshots where this improves chart legibility?

**Comment by fungl164** [comment]
Before
graph1
After
graph2

**Comment by danvk** [comment]
That does look better. How about:

1. Rename `TWO_ANNUAL` and `FIVE_ANNUAL` to match other names.
2. Write an `auto_test`, probably in `auto_tests/tests/date_ticker.js`.

**Comment by danvk** [comment]
There's still no test — I don't accept PRs without unit tests.

**Comment by danvk** [comment]
(Closing due to inactivity)

**Pull request closed without merging**
