### PR TITLE
Updating users.html on source master

### PR DESCRIPTION
**Pull request by JoesephPaulSmith**
Updating Great Lakes Dashboard entry. Prior link was dead.

Apologies for earlier confusion. This is a first time doing a pull request for me...

### CODE REVIEW

**Comment by danvk** [comment]
No worries -- can you take a crack at making this Pull Request a single commit? (I see two identical commits.)

**Comment by JoesephPaulSmith** [comment]
Should be good. Thanks again for your patience

**Comment by danvk** [comment]
Thanks!

**Comment by JoesephPaulSmith** [comment]
Thanks! Have a good one!

**Pull request merged**
